### PR TITLE
[#22][#62] card-bookmarks/screen-size

### PR DESCRIPTION
**Pull request by eddybank**
Added bookmarks to Cryptocurrencies Component and functionality.

Fixed the main routes content width like it was previously.

Several styling changes with Footer and Crypto/News Cards.

Fixed several warnings:
- <p> should not have child <div>
- select in News should have unique keys
- class to className

### CODE REVIEW

**Comment by arnab2001** [comment]
Great job mate , but can you just sync fork/git pull once because some changes has been made to the card component so it's creating merge conflicts

**Comment by arnab2001** [comment]
can you check once again what's causing the merge conflict , i am reviewing but it will be best if you review the merge conflict and keep changes that will work best for the app. Thanks

**Comment by arnab2001** [comment]
hello  @eddybank  , I accepted a bad pr before without much reviewing and it broke some features so I had to make some changes on my own to revert those changes so which may be causing merge conflict to your commit also some minor changes has been done. I tried to resolve merge conflict on my own but couldn't get few things working 
can you please check this pr for one last time and give a pr , I really want to merge your changes to the main .
thanks

**Comment by eddybank** [comment]
@arnab2001 I can get it sorted, but I don't think anything should have been an issue. By the looks of it, pull requests put in after my request (number 62) were merged before mine (which included changes to the card UI). 

I always do a fresh pull of upstream/main to avoid any conflicts but due to myself and others changing the card UI for different purposes and with the order of merging pull requests, my changes are causing issues.

**Pull request merged**
